"use client";
import React, { useMemo, useState, useEffect } from 'react';
import { supabase } from '@/lib/supabase';
import { getCurrentUser, getFinanceSummary } from '@/lib/api';
import { downloadTextFile, renderReportHtml, escapeHtml } from '@/lib/reporting';
import { 
  BarChart3, FileDown, Filter, PieChart, 
  Map, TrendingUp, AlertTriangle, CheckCircle2, 
  ArrowUpRight, ArrowDownRight, Globe, MoreVertical, Search,
  Landmark, Wallet, CalendarCheck, MoreHorizontal
} from 'lucide-react';

export default function ReportsPage() {
  const [isGenerating, setIsGenerating] = useState(false);
  const [role, setRole] = useState(null);
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7));
  const [message, setMessage] = useState(null);

  useEffect(() => {
    getCurrentUser().then((u) => setRole(u?.role || null));
  }, []);

  const permissions = useMemo(() => {
    const r = role || 'student';
    const can = (arr) => arr.includes(r);
    return {
      canStudentReports: can(['coordinator', 'teacher', 'principal', 'admin', 'superadmin']),
      canAcademicReports: can(['coordinator', 'principal', 'admin', 'superadmin']),
      canResultReports: can(['coordinator', 'teacher', 'principal', 'admin', 'superadmin']),
      canFinanceReports: can(['finance', 'admin', 'principal', 'superadmin']),
    };
  }, [role]);

  const runReport = async (type) => {
    setIsGenerating(true);
    setMessage(null);
    try {
      const me = await getCurrentUser();
      const who = me?.full_name || me?.email || 'User';

      if (type === 'finance') {
        if (!permissions.canFinanceReports) throw new Error('You are not allowed to generate finance reports.');
        const fin = await getFinanceSummary(month);
        const html = renderReportHtml({
          title: 'Finance summary report',
          subtitle: 'Completed vs pending totals and category breakdown (month view).',
          meta: [
            { label: 'Month', value: month },
            { label: 'Generated by', value: who },
            { label: 'Role', value: me?.role || '-' },
          ],
          sections: [
            {
              title: 'Totals',
              html: `<table>
                <thead><tr><th>Metric</th><th>Amount</th></tr></thead>
                <tbody>
                  <tr><td>Completed income</td><td>${escapeHtml(String(fin.totalIncome || 0))}</td></tr>
                  <tr><td>Completed expenses</td><td>${escapeHtml(String(fin.totalExpenses || 0))}</td></tr>
                  <tr><td>Pending income</td><td>${escapeHtml(String(fin.pendingIncome || 0))}</td></tr>
                  <tr><td>Pending expenses</td><td>${escapeHtml(String(fin.pendingExpense || 0))}</td></tr>
                  <tr><td><span class="pill">Net position</span></td><td>${escapeHtml(String(fin.netPosition || 0))}</td></tr>
                </tbody>
              </table>`,
            },
            {
              title: 'Income categories (completed)',
              html: `<table><thead><tr><th>Category</th><th>Amount</th></tr></thead><tbody>${
                Object.entries(fin.byCategoryIncome || {})
                  .sort((a, b) => b[1] - a[1])
                  .map(([k, v]) => `<tr><td>${escapeHtml(k)}</td><td>${escapeHtml(String(v))}</td></tr>`)
                  .join('') || `<tr><td class="muted" colspan="2">No income rows</td></tr>`
              }</tbody></table>`,
            },
            {
              title: 'Expense categories (completed)',
              html: `<table><thead><tr><th>Category</th><th>Amount</th></tr></thead><tbody>${
                Object.entries(fin.byCategoryExpense || {})
                  .sort((a, b) => b[1] - a[1])
                  .map(([k, v]) => `<tr><td>${escapeHtml(k)}</td><td>${escapeHtml(String(v))}</td></tr>`)
                  .join('') || `<tr><td class="muted" colspan="2">No expense rows</td></tr>`
              }</tbody></table>`,
            },
          ],
        });

        downloadTextFile({
          filename: `finance_report_${month}_${new Date().toISOString().slice(0, 10)}.html`,
          content: html,
          mime: 'text/html;charset=utf-8',
        });
        setMessage({ type: 'success', text: 'Finance report downloaded as HTML.' });
        return;
      }

      if (type === 'students') {
        if (!permissions.canStudentReports) throw new Error('You are not allowed to generate student reports.');
        const { data: students } = await supabase
          .from('users')
          .select('id, full_name, email, role, created_at')
          .eq('role', 'student')
          .order('created_at', { ascending: false })
          .limit(500);

        const html = renderReportHtml({
          title: 'Student register report',
          subtitle: 'Latest 500 students (for roster/verification).',
          meta: [
            { label: 'Month', value: month },
            { label: 'Generated by', value: who },
            { label: 'Count', value: String(students?.length || 0) },
          ],
          sections: [
            {
              title: 'Students',
              html: `<table>
                <thead><tr><th>Name</th><th>Email</th><th>Joined</th></tr></thead>
                <tbody>${
                  (students || [])
                    .map((s) => {
                      return `<tr><td>${escapeHtml(s.full_name)}</td><td>${escapeHtml(s.email)}</td><td>${escapeHtml(new Date(s.created_at).toLocaleDateString())}</td></tr>`;
                    })
                    .join('') || `<tr><td class="muted" colspan="3">No students found</td></tr>`
                }</tbody>
              </table>`,
            },
          ],
        });

        downloadTextFile({
          filename: `students_report_${month}_${new Date().toISOString().slice(0, 10)}.html`,
          content: html,
          mime: 'text/html;charset=utf-8',
        });
        setMessage({ type: 'success', text: 'Student register downloaded as HTML.' });
        return;
      }

      if (type === 'academic') {
        if (!permissions.canAcademicReports) throw new Error('You are not allowed to generate academic reports.');
        const [{ data: classes }, { data: resources }, { data: curriculum }] = await Promise.all([
          supabase.from('classes').select('id, name, grade_level, section, created_at').order('created_at', { ascending: false }).limit(200),
          supabase.from('resources').select('id, title, type, status, upload_date, is_visible_to_students').order('upload_date', { ascending: false }).limit(400),
          supabase.from('curriculum_alignment').select('id, completion_percentage, last_updated').order('last_updated', { ascending: false }).limit(200),
        ]);

        const statusCounts = (resources || []).reduce((acc, r) => {
          const k = r.status || 'unknown';
          acc[k] = (acc[k] || 0) + 1;
          return acc;
        }, {});

        const avgCompletion =
          (curriculum || []).length > 0
            ? Math.round(
                (curriculum.reduce((sum, c) => sum + parseFloat(c.completion_percentage || 0), 0) /
                  curriculum.length) * 10
              ) / 10
            : 0;

        const html = renderReportHtml({
          title: 'Academic operations report',
          subtitle: 'Classes, resources approval pipeline, and curriculum completion snapshot.',
          meta: [
            { label: 'Month', value: month },
            { label: 'Generated by', value: who },
            { label: 'Avg curriculum', value: `${avgCompletion}%` },
          ],
          sections: [
            {
              title: 'Pipeline summary',
              html: `<table><thead><tr><th>Resource status</th><th>Count</th></tr></thead><tbody>${
                Object.entries(statusCounts)
                  .sort((a, b) => b[1] - a[1])
                  .map(([k, v]) => `<tr><td>${escapeHtml(k)}</td><td>${escapeHtml(String(v))}</td></tr>`)
                  .join('') || `<tr><td class="muted" colspan="2">No resources found</td></tr>`
              }</tbody></table>`,
            },
            {
              title: 'Classes (latest)',
              html: `<table><thead><tr><th>Class</th><th>Grade</th><th>Section</th><th>Created</th></tr></thead><tbody>${
                (classes || [])
                  .map((c) => `<tr><td>${escapeHtml(c.name)}</td><td>${escapeHtml(c.grade_level)}</td><td>${escapeHtml(c.section || '-')}</td><td>${escapeHtml(new Date(c.created_at).toLocaleDateString())}</td></tr>`)
                  .join('') || `<tr><td class="muted" colspan="4">No classes</td></tr>`
              }</tbody></table>`,
            },
          ],
        });

        downloadTextFile({
          filename: `academic_report_${month}_${new Date().toISOString().slice(0, 10)}.html`,
          content: html,
          mime: 'text/html;charset=utf-8',
        });
        setMessage({ type: 'success', text: 'Academic operations report downloaded as HTML.' });
        return;
      }

      if (type === 'results') {
        if (!permissions.canResultReports) throw new Error('You are not allowed to generate result reports.');
        const { data: gradeRows } = await supabase
          .from('grades')
          .select('id, student_id, subject_id, marks_obtained, total_marks, term, recorded_date')
          .order('recorded_date', { ascending: false })
          .limit(1000);

        const avg =
          (gradeRows || []).length > 0
            ? Math.round(
                (gradeRows.reduce((sum, g) => sum + (parseFloat(g.marks_obtained || 0) / parseFloat(g.total_marks || 100)) * 100, 0) /
                  gradeRows.length) * 10
              ) / 10
            : 0;

        const html = renderReportHtml({
          title: 'Results performance report',
          subtitle: 'Grade entry health + average performance across latest grade rows.',
          meta: [
            { label: 'Month', value: month },
            { label: 'Generated by', value: who },
            { label: 'Avg %', value: `${avg}%` },
          ],
          sections: [
            {
              title: 'Latest grade rows',
              html: `<table><thead><tr><th>Term</th><th>Student</th><th>Subject</th><th>Marks</th><th>Date</th></tr></thead><tbody>${
                (gradeRows || [])
                  .slice(0, 120)
                  .map((g) => `<tr><td>${escapeHtml(g.term || '-')}</td><td>${escapeHtml(g.student_id)}</td><td>${escapeHtml(g.subject_id)}</td><td>${escapeHtml(String(g.marks_obtained || 0))}/${escapeHtml(String(g.total_marks || 100))}</td><td>${escapeHtml(new Date(g.recorded_date).toLocaleDateString())}</td></tr>`)
                  .join('') || `<tr><td class="muted" colspan="5">No grade rows</td></tr>`
              }</tbody></table>`,
            },
          ],
        });

        downloadTextFile({
          filename: `results_report_${month}_${new Date().toISOString().slice(0, 10)}.html`,
          content: html,
          mime: 'text/html;charset=utf-8',
        });
        setMessage({ type: 'success', text: 'Results report downloaded as HTML.' });
        return;
      }

      throw new Error('Unknown report type.');
    } catch (e) {
      setMessage({ type: 'error', text: e?.message || 'Failed to generate report.' });
    } finally {
      setIsGenerating(false);
    }
  };

  const lens =
    role === 'admin'
      ? {
          title: 'Operations & fee intelligence',
          subtitle: 'Designed for registrars: collections, fee slips, parent comms, and payroll snapshots.',
        }
      : {
          title: 'National performance analytics',
          subtitle: 'Principal view: academic throughput, campus benchmarks, and governance-ready exports.',
        };

  return (
    <div className="space-y-10 animate-fade-in font-sans pb-20 dark:text-slate-200">
      
      {/* 1. TOP HEADER & BREADCRUMB */}
      <div className="flex flex-col xl:flex-row xl:justify-between xl:items-end gap-8">
        <div className="space-y-1">
          <div className="flex items-center gap-2 text-[10px] font-bold text-slate-300 dark:text-slate-600 uppercase tracking-[0.3em]">
             Dashboard <span className="text-slate-200 dark:text-slate-700">/</span> <span className="text-indigo-400 dark:text-indigo-500">Reports & Analytics</span>
          </div>
          <h1 className="text-4xl font-light text-slate-950 dark:text-white tracking-tight mt-2">{lens.title}</h1>
          <p className="text-slate-400 dark:text-slate-500 text-sm font-light max-w-2xl">{lens.subtitle}</p>
          {role && (
            <p className="text-[10px] uppercase tracking-[0.35em] font-bold text-indigo-500 dark:text-indigo-400 pt-2">
              Signed in as {role}
            </p>
          )}
        </div>
        <div className="flex flex-col sm:flex-row gap-3 sm:items-center justify-end">
          <label className="flex items-center gap-2 px-4 py-3 border border-slate-100 dark:border-white/10 rounded-xl text-[11px] font-bold uppercase tracking-widest text-slate-600 dark:text-slate-300 bg-white dark:bg-slate-900 shadow-sm">
            <CalendarCheck size={14} />
            <input
              type="month"
              value={month}
              onChange={(e) => setMonth(e.target.value)}
              className="bg-transparent outline-none font-mono text-[12px]"
            />
          </label>
          <button
            type="button"
            disabled={isGenerating}
            onClick={() => runReport('students')}
            className="flex items-center gap-2 px-6 py-3 border border-slate-100 dark:border-white/10 rounded-xl text-[11px] font-bold uppercase tracking-widest text-slate-600 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-white/5 transition-all disabled:opacity-60"
          >
            <BarChart3 size={14} /> Student report
          </button>
          <button
            type="button"
            disabled={isGenerating}
            onClick={() => runReport('academic')}
            className="flex items-center gap-2 px-6 py-3 border border-slate-100 dark:border-white/10 rounded-xl text-[11px] font-bold uppercase tracking-widest text-slate-600 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-white/5 transition-all disabled:opacity-60"
          >
            <PieChart size={14} /> Academic report
          </button>
          <button
            type="button"
            disabled={isGenerating}
            onClick={() => runReport('results')}
            className="flex items-center gap-2 px-6 py-3 border border-slate-100 dark:border-white/10 rounded-xl text-[11px] font-bold uppercase tracking-widest text-slate-600 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-white/5 transition-all disabled:opacity-60"
          >
            <FileDown size={14} /> Result report
          </button>
          <button
            type="button"
            disabled={isGenerating || !permissions.canFinanceReports}
            onClick={() => runReport('finance')}
            className="flex items-center gap-2 px-6 py-3 bg-slate-950 dark:bg-indigo-600 text-white rounded-xl text-[11px] font-bold uppercase tracking-widest shadow-xl hover:bg-black dark:hover:bg-indigo-700 transition-all disabled:opacity-50"
            title={permissions.canFinanceReports ? 'Generate finance report' : 'Restricted: finance only'}
          >
            {isGenerating ? <div className="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin"></div> : <Wallet size={14} />}
            Finance report
          </button>
        </div>
      </div>

      {message && (
        <div
          className={`p-4 rounded-xl border ${
            message.type === 'success'
              ? 'bg-emerald-50 dark:bg-emerald-500/10 border-emerald-200 dark:border-emerald-500/20 text-emerald-700 dark:text-emerald-300'
              : 'bg-rose-50 dark:bg-rose-500/10 border-rose-200 dark:border-rose-500/20 text-rose-700 dark:text-rose-300'
          }`}
        >
          <p className="text-sm font-medium">{message.text}</p>
        </div>
      )}

      {/* 2. ANALYTICS GRID */}
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
        
        {/* Left Stats Column */}
        <div className="space-y-6">
           <SmallReportCard title="Total Enrollment" value="142,580" trend="+12.4%" sub="vs Last Session" />
           <SmallReportCard title="Avg. Academic Score" value="76.8%" trend="Target: 80%" sub="Across 482 Campuses" progress={76} />
           <SmallReportCard title="Total Fee Collection" value="PKR 84.2M" trend="-2.1%" sub="Pending Dues: 4.5M" isNegative />
        </div>

        {/* Center: Provincial Chart */}
        <div className="lg:col-span-2 bg-white dark:bg-slate-900 border border-slate-100 dark:border-white/5 rounded-[2.5rem] p-10 flex flex-col justify-between">
           <div className="flex justify-between items-start">
              <div>
                <h3 className="text-xl font-light text-slate-800 dark:text-white tracking-tight">Academic Score by Province</h3>
                <div className="flex gap-4 mt-2">
                   <div className="flex items-center gap-2 text-[9px] font-bold uppercase text-slate-400 dark:text-slate-500 tracking-widest"><div className="w-2 h-2 bg-slate-900 dark:bg-slate-100 rounded-full"></div> Board Exams</div>
                   <div className="flex items-center gap-2 text-[9px] font-bold uppercase text-slate-400 dark:text-slate-500 tracking-widest"><div className="w-2 h-2 bg-emerald-500 rounded-full"></div> Internal</div>
                </div>
              </div>
           </div>
           
           <div className="h-64 flex items-end justify-between px-2 pt-10">
              {/* Regional Bar Groups */}
              <BarGroup label="PUNJAB" h1={80} h2={60} />
              <BarGroup label="SINDH" h1={70} h2={50} />
              <BarGroup label="KPK" h1={90} h2={75} />
              <BarGroup label="BALOCH" h1={45} h2={40} />
              <BarGroup label="FEDERAL" h1={95} h2={80} />
           </div>
        </div>

        {/* Right: Feature Box */}
        <div className="bg-gradient-to-br from-slate-950 dark:from-indigo-950 to-indigo-950 dark:to-indigo-900 rounded-[2.5rem] p-10 text-white relative overflow-hidden flex flex-col justify-between">
           <div className="absolute top-0 right-0 w-64 h-64 bg-white/5 rounded-full -translate-y-1/2 translate-x-1/2"></div>
           <div>
              <h3 className="text-xl font-light tracking-tight mb-2">New Campus Request</h3>
              <p className="text-slate-400 dark:text-slate-500 text-xs leading-relaxed">3 Pending Approvals in Bahawalpur District, Punjab.</p>
           </div>
           
           <div className="space-y-4">
              <div className="w-full h-1 bg-white/10 rounded-full">
                 <div className="w-[84%] h-full bg-indigo-400"></div>
              </div>
              <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-slate-400 dark:text-slate-500">Geographic Density: 84%</p>
           </div>

           <button className="w-full py-4 bg-white text-slate-950 dark:text-indigo-600 text-[10px] font-bold uppercase tracking-[0.3em] rounded-xl hover:bg-slate-50 dark:hover:bg-white transition-all">
              View Provincial Heatmap
           </button>
        </div>
      </div>

      {/* 3. RANKINGS TABLE */}
      <div className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-white/5 rounded-[2.5rem] shadow-sm overflow-hidden">
        <div className="p-10 flex justify-between items-center border-b border-slate-50 dark:border-white/5">
           <h3 className="text-xl font-light text-slate-900 dark:text-white tracking-tight">Campus Benchmark Rankings</h3>
           <div className="relative">
              <Search className="absolute left-3 top-3 text-slate-300 dark:text-slate-600" size={14}/>
              <input className="pl-10 pr-4 py-2.5 bg-slate-50 dark:bg-white/5 border border-slate-100 dark:border-white/10 rounded-xl text-[11px] font-medium outline-none focus:ring-1 ring-indigo-200 dark:ring-indigo-500/30 dark:text-slate-300" placeholder="Find Campus..."/>
           </div>
        </div>
        <table className="w-full text-left">
           <thead>
              <tr className="text-[10px] uppercase font-bold text-slate-400 dark:text-slate-500 bg-slate-50/50 dark:bg-white/5 border-b border-slate-100 dark:border-white/5">
                 <th className="px-10 py-5">Campus Name</th>
                 <th className="px-10 py-5">Province</th>
                 <th className="px-10 py-5">Enrollment</th>
                 <th className="px-10 py-5">Avg. Performance</th>
                 <th className="px-10 py-5">Status</th>
              </tr>
           </thead>
           <tbody className="divide-y divide-slate-50 dark:divide-white/5 text-sm">
              <ReportRow name="EduPro Academy - Lahore Central" id="PK-PB-001" province="Punjab" users="2,450" score="88.4%" top />
              <ReportRow name="Karachi Grammar International" id="PK-SN-042" province="Sindh" users="3,120" score="72.1%" />
              <ReportRow name="Peshawar Model High" id="PK-KP-018" province="KPK" users="1,890" score="58.9%" warning />
           </tbody>
        </table>
      </div>

      {/* 4. INSIGHTS SECTION */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 pt-6">
         <div className="space-y-6">
            <h3 className="flex items-center gap-3 text-[12px] font-bold text-slate-900 dark:text-white uppercase tracking-widest"><TrendingUp size={16} className="text-indigo-500 dark:text-indigo-400"/> Administrative Insights</h3>
            <InsightItem color="border-l-blue-600 dark:border-l-blue-400" title="Board Exam Trend" desc="Science subjects in Central Punjab show a 15% improvement in results compared to previous cycle." />
            <InsightItem color="border-l-rose-500 dark:border-l-rose-400" title="Fee Collection Alert" desc="Southern Sindh campuses are experiencing a 22% delay in fee submission. Review SMS alerts." />
         </div>

         <div className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-white/5 rounded-[2.5rem] p-10 space-y-8">
            <h3 className="text-[12px] font-bold text-slate-900 dark:text-white uppercase tracking-widest">Enrollment Pipeline (Next Session)</h3>
            <div className="space-y-6">
               <Pipeline label="Admissions Applied" current="42,000" target="50,000" color="bg-indigo-600 dark:bg-indigo-500" />
               <Pipeline label="Entrance Tests Cleared" current="18,500" target="42,000" color="bg-emerald-500 dark:bg-emerald-400" />
               <Pipeline label="Vouchers Generated" current="12,100" target="18,500" color="bg-orange-400 dark:bg-orange-500" />
            </div>
         </div>
      </div>

    </div>
  );
}

// Minimalist Sub-Components
function SmallReportCard({ title, value, trend, sub, isNegative, progress }) {
  return (
    <div className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-white/5 rounded-[2rem] p-8 shadow-sm group hover:border-indigo-100 dark:hover:border-indigo-500/20 transition-all">
       <p className="text-[10px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest mb-1">{title}</p>
       <h2 className="text-3xl font-light text-slate-950 dark:text-white tracking-tighter mb-4">{value}</h2>
       <div className="flex items-center gap-2 mb-2">
          <span className={`text-[10px] font-black px-2 py-0.5 rounded ${isNegative ? 'bg-rose-50 dark:bg-rose-500/10 text-rose-500 dark:text-rose-400' : 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400'}`}>
            {isNegative ? <ArrowDownRight size={10} className="inline mr-1"/> : <ArrowUpRight size={10} className="inline mr-1"/>}
            {trend}
          </span>
          <span className="text-[10px] font-medium text-slate-300 dark:text-slate-700 uppercase tracking-widest">{sub}</span>
       </div>
       {progress && (
         <div className="w-full h-1 bg-slate-50 dark:bg-white/5 rounded-full mt-4 overflow-hidden">
            <div style={{width: `${progress}%`}} className="h-full bg-indigo-500 dark:bg-indigo-400"></div>
         </div>
       )}
    </div>
  );
}

function BarGroup({ label, h1, h2 }) {
  return (
    <div className="flex flex-col items-center gap-4 h-full flex-1 group">
       <div className="flex items-end gap-1.5 h-full relative">
          <div style={{height: `${h1}%`}} className="w-8 bg-slate-900 dark:bg-slate-100 rounded-t-lg transition-all group-hover:bg-indigo-600 dark:group-hover:bg-indigo-400"></div>
          <div style={{height: `${h2}%`}} className="w-8 bg-slate-100 dark:bg-slate-800 rounded-t-lg transition-all group-hover:bg-emerald-100 dark:group-hover:bg-emerald-600"></div>
       </div>
       <p className="text-[9px] font-bold text-slate-300 dark:text-slate-700 uppercase tracking-widest">{label}</p>
    </div>
  );
}

function ReportRow({ name, id, province, users, score, top, warning }) {
  return (
    <tr className="hover:bg-slate-50 dark:hover:bg-white/5 transition-colors">
       <td className="px-10 py-6">
          <p className="text-[13px] font-bold text-slate-950 dark:text-white">{name}</p>
          <p className="text-[10px] text-slate-400 dark:text-slate-500 font-medium">ID: {id}</p>
       </td>
       <td className="px-10 py-6 text-slate-500 dark:text-slate-400 font-medium">{province}</td>
       <td className="px-10 py-6 text-slate-500 dark:text-slate-400 font-medium">{users}</td>
       <td className="px-10 py-6">
          <span className={`text-[12px] font-bold ${warning ? 'text-rose-500 dark:text-rose-400' : 'text-slate-950 dark:text-white'}`}>{score}</span>
          {top && <span className="ml-3 px-2 py-0.5 bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 text-[9px] font-black uppercase rounded">Top 5%</span>}
       </td>
       <td className="px-10 py-6">
          <span className={`text-[9px] font-black px-3 py-1 rounded-full uppercase tracking-widest border ${warning ? 'bg-rose-50 dark:bg-rose-500/10 text-rose-600 dark:text-rose-400 border-rose-100 dark:border-rose-500/20' : 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-100 dark:border-emerald-500/20'}`}>
            {warning ? 'At Risk' : 'Optimal'}
          </span>
       </td>
    </tr>
  );
}

function InsightItem({ title, desc, color }) {
  return (
    <div className={`p-6 bg-white dark:bg-slate-900 border border-slate-100 dark:border-white/5 border-l-4 ${color} rounded-2xl shadow-sm space-y-2`}>
       <h4 className="text-[13px] font-bold text-slate-800 dark:text-white">{title}</h4>
       <p className="text-[11px] text-slate-500 dark:text-slate-400 leading-relaxed font-light">{desc}</p>
    </div>
  );
}

function Pipeline({ label, current, target, color }) {
  const percent = (parseInt(current.replace(',','')) / parseInt(target.replace(',',''))) * 100;
  return (
    <div className="space-y-3">
       <div className="flex justify-between items-center text-[10px] font-bold uppercase tracking-widest">
          <span className="text-slate-400 dark:text-slate-500">{label}</span>
          <span className="text-slate-900 dark:text-white">{current} <span className="text-slate-200 dark:text-slate-700">/</span> {target}</span>
       </div>
       <div className="w-full h-2 bg-slate-50 dark:bg-white/5 rounded-full overflow-hidden border border-slate-100 dark:border-white/10">
          <div style={{width: `${percent}%`}} className={`h-full ${color} transition-all duration-1000`}></div>
       </div>
    </div>
  );
}