export function downloadTextFile({ filename, content, mime = 'text/plain;charset=utf-8' }) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function escapeHtml(value) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

export function renderReportHtml({ title, subtitle, meta = [], sections = [] }) {
  const metaHtml = meta
    .map(({ label, value }) => {
      return `<div class="metaBox"><div class="metaLabel">${escapeHtml(label)}</div><div class="metaValue">${escapeHtml(value)}</div></div>`;
    })
    .join('');

  const sectionsHtml = sections
    .map((s) => {
      const body = s.html || '';
      return `<section class="section"><h2>${escapeHtml(s.title)}</h2>${body}</section>`;
    })
    .join('');

  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(title)}</title>
    <style>
      :root { --ink:#0b1220; --muted:#64748b; --line:#e2e8f0; --brand:#4f46e5; --bg:#ffffff; }
      body { font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif; margin: 32px; color: var(--ink); background: var(--bg); }
      .header { border-bottom: 3px solid var(--ink); padding-bottom: 14px; margin-bottom: 20px; }
      .title { margin: 0; letter-spacing: -0.02em; font-weight: 700; font-size: 24px; }
      .subtitle { margin: 6px 0 0; color: var(--muted); font-size: 13px; }
      .metaGrid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 10px; margin: 18px 0 0; }
      .metaBox { border: 1px solid var(--line); border-radius: 12px; padding: 10px 12px; }
      .metaLabel { font-size: 10px; letter-spacing: .18em; text-transform: uppercase; color: var(--muted); font-weight: 700; }
      .metaValue { margin-top: 4px; font-size: 13px; font-weight: 600; }
      .section { margin-top: 20px; border: 1px solid var(--line); border-radius: 16px; padding: 16px; }
      .section h2 { margin: 0 0 10px; font-size: 13px; letter-spacing: .22em; text-transform: uppercase; color: var(--brand); }
      table { width: 100%; border-collapse: collapse; font-size: 12px; }
      th, td { border-bottom: 1px solid var(--line); padding: 10px 8px; text-align: left; vertical-align: top; }
      th { font-size: 10px; letter-spacing: .18em; text-transform: uppercase; color: var(--muted); font-weight: 800; }
      .pill { display:inline-block; padding: 4px 8px; border-radius: 999px; background: #eef2ff; color: #3730a3; font-weight: 700; font-size: 10px; letter-spacing: .08em; text-transform: uppercase; }
      .muted { color: var(--muted); }
      @media print { body { margin: 18px; } .section { break-inside: avoid; } }
    </style>
  </head>
  <body>
    <div class="header">
      <h1 class="title">${escapeHtml(title)}</h1>
      <p class="subtitle">${escapeHtml(subtitle)}</p>
      ${metaHtml ? `<div class="metaGrid">${metaHtml}</div>` : ''}
    </div>
    ${sectionsHtml}
    <p class="muted" style="margin-top:18px;font-size:11px;">Generated by Academia LMS • ${escapeHtml(new Date().toLocaleString())}</p>
  </body>
</html>`;
}

